# Generated by Django 3.2 on 2021-04-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_testimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestImage',
        ),
    ]
